<?php

namespace Tahadudhiya\SmartLinks\models;

use craft\helpers\StringHelper;
use Tahadudhiya\SmartLinks\enums\LinkFeature;
use Tahadudhiya\SmartLinks\linktypes\LinkTypeDataInterface;

/**
 * One link as its author made it: the normalized, stored definition.
 *
 * It holds only what content decides. Where the link leads, its target identity, its health and
 * its usage are derived elsewhere. Its rules live in {@see \Tahadudhiya\SmartLinks\links\LinkValidator}:
 * values that come from the normalizer or the serializer have passed it, and the serializer
 * refuses to store one that has not.
 */
final class LinkValue
{
    /**
     * @param string $uid The occurrence's identity within its value, a lowercase UUID v4. It
     * survives edits, reordering and target changes, so it is only generated by {@see create()}.
     * @param string $type The link type's handle.
     * @param LinkTypeDataInterface $data The link type's own data.
     * @param string|null $urlSuffix A query or fragment the resolver appends to the URL.
     * @param string|null $presetUid The preset the link was authored from. A reference only.
     */
    public function __construct(
        public readonly string $uid,
        public readonly string $type,
        public readonly LinkTypeDataInterface $data,
        public readonly ?string $label = null,
        public readonly ?string $urlSuffix = null,
        public readonly LinkAttributes $attributes = new LinkAttributes(),
        public readonly ?string $presetUid = null,
    ) {
    }

    /**
     * A new occurrence of a link, with a newly generated UID.
     */
    public static function create(
        string $type,
        LinkTypeDataInterface $data,
        ?string $label = null,
        ?string $urlSuffix = null,
        LinkAttributes $attributes = new LinkAttributes(),
        ?string $presetUid = null,
    ): self {
        return new self(StringHelper::UUID(), $type, $data, $label, $urlSuffix, $attributes, $presetUid);
    }

    /**
     * The optional features this link uses, which its type must support.
     *
     * @return list<LinkFeature>
     */
    public function usedFeatures(): array
    {
        $features = $this->attributes->usedFeatures();

        if ($this->urlSuffix !== null) {
            array_unshift($features, LinkFeature::URL_SUFFIX);
        }

        return $features;
    }
}
